---
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: uWSGI

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20", "1.21"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: test/requirements.txt

      - name: Install uWSGI
        run: pip install --upgrade -r test/requirements.txt

      - name: Build
        run: xcaddy build --with github.com/BadAimWeeb/caddy-uwsgi-transport=.

      - name: Test
        run: timeout 1m ./test/test.sh
